// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3BdjtszumuSJjWZlLVf2Kk0UVdoPZzU',
    appId: '1:903819287832:web:9a379cd83dbc707356526d',
    messagingSenderId: '903819287832',
    projectId: 'test-a07e4',
    authDomain: 'test-a07e4.firebaseapp.com',
    storageBucket: 'test-a07e4.appspot.com',
    measurementId: 'G-64ZL7YNQPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4AlI0P1gT6KK3NNkZ2w0N6w2an4ajIs',
    appId: '1:903819287832:android:a752ad4d9263691556526d',
    messagingSenderId: '903819287832',
    projectId: 'test-a07e4',
    storageBucket: 'test-a07e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA6NZZ7aT-pIF-zpPXs0OHNSyGDtQgIKM',
    appId: '1:903819287832:ios:bf00e8aeefda04d656526d',
    messagingSenderId: '903819287832',
    projectId: 'test-a07e4',
    storageBucket: 'test-a07e4.appspot.com',
    iosClientId: '903819287832-vtt7hdqc34t4uv2s6hn4i3br4op90juu.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA6NZZ7aT-pIF-zpPXs0OHNSyGDtQgIKM',
    appId: '1:903819287832:ios:bf00e8aeefda04d656526d',
    messagingSenderId: '903819287832',
    projectId: 'test-a07e4',
    storageBucket: 'test-a07e4.appspot.com',
    iosClientId: '903819287832-vtt7hdqc34t4uv2s6hn4i3br4op90juu.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
